### ISSUE TITLE
Arbitrary grid size problems.

### ISSUE THREAD

**Issue by vrod** [gpoesia/comp4kids#12]
As of now, the optimum grid size is 10x10. That means when a grid smaller than 10x10 is created, it occupies less space than made available in canvas. It is more critical for grids greater than 10x10, that end up rendered out of canvas.

**Comment by gpoesia** [comment]
Working on it. I'm allowing the animator to accept an "origin", so that we can render a smaller grid in the middle of the canvas (without changing the animations themselves). Besides that, I'm making the grid size be customizable by each lesson step (with the default being 10), and the responsibility of setting up the canvas with the correct coordinate space width and height gets delegated to LessonStep::reset.
