### ISSUE TITLE
Do not reset when the code is modified 

### ISSUE THREAD

**Issue by gpoesia** [gpoesia/comp4kids#44]
Right now, when the code is modified, the game is reset to its initial state. Some students prefer to write code incrementally (which is good), and this hinders them, since they cannot see in which state the existing code ends and build upon that. Modifying the code should probably not immediately reset the game. There's already a reset button if the student wants that.

The modification involved would probably be to simply not call _reset() in LessonEnvironment.componentDidUpdate() (https://github.com/gpoesia/comp4kids/blob/master/src/view/lesson_environment.js#L164)

**Comment by msclar** [comment]
Not calling _reset() is not the only change to be made because when you do that, it avoids a necessary reset between levels and shows the final state of the previous level. 

For some reason, calling _reset() inside _advanceStep() also doesn't work because it won't update the level rendering (it will show again the previous level from the beginning, until you press the "reset" button, then it shows the next level). I'm guessing the level number is not being updated by the time I call _reset().

I will dig further into this, I think I just need to find the appropriate place to do the reset.

**Comment by gpoesia** [comment]
Oh, right. What you said about the level number not being updated might be correct. When you call `setState` in React, the state is not immediately updated. When it is, a new rendering is performed. Maybe reset should go in `render()`?
