### ISSUE TITLE
Code Editor should be focused when the level starts

### ISSUE THREAD

**Issue by gpoesia** [gpoesia/comp4kids#51]
One issue that confuses students is that the Code Editor loses focus when they advance to the next step. Then, many times they start typing and only then realise they need to click the editor first. Focusing the editor by default when a new step begins would solve this problem.

The implementation would be basically to give focus to CodeEditor's `<textarea>` element whenever it is rendered. This would involve the following:
- Set a "ref" callback to CodeEditor's `<textarea>` element, so that it can be accessed after rendering is done (https://facebook.github.io/react/docs/more-about-refs.html)
- In that callback, call the element's `focus` method (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus)

There's a chance this will not work because of the pop-up we show in the beginning of the step. If so, we'll probably need to call `focus` when the pop-up is closed. By looking at `react-popup`'s code, it seems this can be done using `popup.addCloseListener(callback)` (https://github.com/minutemailer/react-popup/blob/master/src/index.js). Then, this callback would need to indirectly call `textarea.focus()`.

**Comment by msclar** [comment]
You were right, the first approach does not work because of the pop-up. It focuses on CodeEditor's `<textarea>` while the popup is showing, but it defocuses upon closing.

Regarding the second approach, I'm not being able to make it work: addCloseListener() seems to never be triggered. I tried with various simple functions that should have a visual effect but none was showed.
